name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # Uruchamiaj przy pushu do głównej gałęzi

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build Wasm
        run: ./gradlew :composeApp:wasmJsBrowserDistribution

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: composeApp/build/dist/wasmJs/productionExecutable
          branch: gh-pages # Pliki trafią na ten branch